name: tempgres-client
version: "1.0.0"
synopsis: Client library for Tempgres.
description: >
  Client library for <https://github.com/ClockworkConsulting/tempgres-server Tempgres>
  for conveniently creating temporary PostgreSQL databases for use in tests.
category: "Database, Testing"
license: BSD2
license-file: LICENSE.txt
author: Bardur Arantsson
maintainer: bardur@scientician.net
copyright: Copyright (c) 2014-2023 Bardur Arantsson
github: ClockworkConsulting/tempgres-client-hs

ghc-options: -Wall

default-extensions:
  - ImportQualifiedPost

dependencies:
  - base == 4.*
  - bytestring >= 0.9.0.1
  - HTTP >= 4000.2.17 && < 4001

library:
  exposed-modules:
    - Database.Tempgres.Client
  source-dirs: src
